[package]
name = 'membership-supernodes'
version = '2.0.0'
authors = ['Parity Technologies <admin@parity.io>', 'Luke Schoen <luke@mxc.org>']
edition = '2018'
license = 'Apache-2.0'
homepage = 'https://substrate.dev'
repository = 'https://github.com/paritytech/substrate/'
description = 'Modification of FRAME membership management pallet where only Sudo authorised to call methods'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { version = '1.2.0', package = 'parity-scale-codec', default-features = false, features = ['derive'] }
frame-support = { version = '2.0.0', default-features = false }
frame-system = { version = '2.0.0', default-features = false }
pallet-sudo = { version = '2.0.0', default-features = false }
sp-core = { version = '2.0.0', default-features = false }
sp-io = { version = '2.0.0', default-features = false }
sp-runtime = { version = '2.0.0', default-features = false }
sp-std = { version = '2.0.0', default-features = false }

serde = { version = '1.0.101', optional = true }

[dev-dependencies]

[features]
default = ['std']
std = [
	'codec/std',
	'frame-support/std',
	'frame-system/std',
	'pallet-sudo/std',
	'sp-io/std',
	'sp-runtime/std',
	'sp-std/std',
	'serde',
]
