language: rust
branches:
  only:
    - master
    - os: linux
      rust: stable
      before_script:
        - rustup component add rustfmt
        - sudo apt-get -y update
        - sudo apt-get install -y cmake libclang-dev pkg-config libssl-dev
        - rustup toolchain install stable
        - rustup update
        - cargo update
script:
  - cargo fmt -- --check
  - cargo check --all --tests
  - cargo build --all
  - cargo test -p node-runtime