language: rust
branches:
  only:
    - master
    - os: linux
      rust: stable
      before_script:
        - rustup component add rustfmt
        - sudo apt-get -y update
        - sudo apt-get install -y cmake libclang-dev pkg-config libssl-dev
        - rustup toolchain install stable
        - rustup toolchain install nightly
        - rustup target add wasm32-unknown-unknown --toolchain nightly
        - rustup component add rustfmt
        - rustup set profile default
        - rustup update
        - cargo update
script:
  - cargo fmt -- --check || true
  - cargo build --all
  - cargo test -p node-runtime