[package]
authors = ['MXC Foundation GmbH <https://t.me/mxcfoundation>', 'Luke Schoen <luke@mxc.org>']
build = 'build.rs'
edition = '2018'
name = 'node'
version = '2.0.0'

[[bin]]
name = 'node'
path = 'src/main.rs'

[dependencies]
futures = '0.3.1'
log = '0.4.8'
structopt = '0.3.8'

grandpa = { version = '0.8', package = 'sc-finality-grandpa', rev = 'b27d50c4c7b7137f2de04c31092f63a58970d0cb', git = 'https://github.com/paritytech/substrate.git' }
grandpa-primitives = { version = '2.0.0', package = 'sp-finality-grandpa', rev = 'b27d50c4c7b7137f2de04c31092f63a58970d0cb', git = 'https://github.com/paritytech/substrate.git' }
sc-basic-authorship = { rev = 'b27d50c4c7b7137f2de04c31092f63a58970d0cb', git = 'https://github.com/paritytech/substrate.git' }
sc-cli = { version = '0.8.0', rev = 'b27d50c4c7b7137f2de04c31092f63a58970d0cb', git = 'https://github.com/paritytech/substrate.git' }
sc-client = { version = '0.8', rev = 'b27d50c4c7b7137f2de04c31092f63a58970d0cb', git = 'https://github.com/paritytech/substrate.git' }
sc-consensus-aura = { version = '0.8', rev = 'b27d50c4c7b7137f2de04c31092f63a58970d0cb', git = 'https://github.com/paritytech/substrate.git' }
sc-executor = { version = '0.8', rev = 'b27d50c4c7b7137f2de04c31092f63a58970d0cb', git = 'https://github.com/paritytech/substrate.git' }
sc-network = { version = '0.8', rev = 'b27d50c4c7b7137f2de04c31092f63a58970d0cb', git = 'https://github.com/paritytech/substrate.git' }
sc-service = { version = '0.8', rev = 'b27d50c4c7b7137f2de04c31092f63a58970d0cb', git = 'https://github.com/paritytech/substrate.git' }
sc-transaction-pool = { version = '2.0.0', rev = 'b27d50c4c7b7137f2de04c31092f63a58970d0cb', git = 'https://github.com/paritytech/substrate.git' }
sp-consensus-aura = { version = '0.8', rev = 'b27d50c4c7b7137f2de04c31092f63a58970d0cb', git = 'https://github.com/paritytech/substrate.git' }
sp-consensus = { version = '0.8', rev = 'b27d50c4c7b7137f2de04c31092f63a58970d0cb', git = 'https://github.com/paritytech/substrate.git' }
sp-core = { version = '2.0.0', default_features = false, rev = 'b27d50c4c7b7137f2de04c31092f63a58970d0cb', git = 'https://github.com/paritytech/substrate.git' }
sp-inherents = { version = '2.0.0', rev = 'b27d50c4c7b7137f2de04c31092f63a58970d0cb', git = 'https://github.com/paritytech/substrate.git' }
sp-runtime = { version = '2.0.0', rev = 'b27d50c4c7b7137f2de04c31092f63a58970d0cb', git = 'https://github.com/paritytech/substrate.git' }
sp-transaction-pool = { version = '2.0.0', rev = 'b27d50c4c7b7137f2de04c31092f63a58970d0cb', git = 'https://github.com/paritytech/substrate.git' }

node-runtime = { version = '2.0.0', path = 'runtime' }

[build-dependencies]
vergen = '3.0.4'
build-script-utils = { version = '2.0.0', rev = 'b27d50c4c7b7137f2de04c31092f63a58970d0cb', package = 'substrate-build-script-utils', git = 'https://github.com/paritytech/substrate.git' }

[workspace]
members = [
    'runtime',
    'pallets/roaming/roaming-operators',
    'pallets/roaming/roaming-networks',
    'pallets/roaming/roaming-organizations',
    'pallets/roaming/roaming-network-servers',
    'pallets/roaming/roaming-devices',
    'pallets/roaming/roaming-routing-profiles',
    'pallets/roaming/roaming-service-profiles',
    'pallets/roaming/roaming-accounting-policies',
    'pallets/roaming/roaming-agreement-policies',
    'pallets/roaming/roaming-network-profiles',
    # 'pallets/roaming/roaming-device-profiles',
    # 'pallets/roaming/roaming-sessions',
    # 'pallets/roaming/roaming-billing-policies',
    # 'pallets/roaming/roaming-charging-policies',
    # 'pallets/roaming/roaming-packet-bundles',
    # 'pallets/mining/mining-speed-boosts/configuration/token-mining',
    # 'pallets/mining/mining-speed-boosts/configuration/hardware-mining',
    # 'pallets/mining/mining-speed-boosts/rates/token-mining',
    # 'pallets/mining/mining-speed-boosts/rates/hardware-mining',
    # 'pallets/mining/mining-speed-boosts/sampling/token-mining',
    # 'pallets/mining/mining-speed-boosts/sampling/hardware-mining',
    # 'pallets/mining/mining-speed-boosts/eligibility/token-mining',
    # 'pallets/mining/mining-speed-boosts/eligibility/hardware-mining',
    # 'pallets/mining/mining-speed-boosts/claims/token-mining',
    # 'pallets/mining/mining-speed-boosts/claims/hardware-mining',
]
