[profile.release]
panic = 'unwind'

[package]
authors = ['MXC Foundation GmbH <https://t.me/mxcfoundation>', 'Luke Schoen <luke@mxc.org>']
build = 'build.rs'
edition = '2018'
name = 'node'
version = '2.0.0'

[build-dependencies]
vergen = '3.0.4'

[build-dependencies.build-script-utils]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-build-script-utils'
rev = '3e651110aa06aa835790df63410a29676243fc54'
version = '2.0.0'

[dependencies]
futures = '0.3.1'
log = '0.4.8'
parking_lot = '0.9.0'
tokio = '0.1.22'
trie-root = '0.15.2'

[dependencies.codec]
package = 'parity-scale-codec'
version = '1.0.0'

[dependencies.ctrlc]
features = ['termination']
version = '3.1.3'

[dependencies.futures01]
package = 'futures'
version = '0.1.29'

[dependencies.grandpa]
git = 'https://github.com/paritytech/substrate.git'
package = 'sc-finality-grandpa'
rev = '3e651110aa06aa835790df63410a29676243fc54'
version = '2.0.0'

[dependencies.grandpa-primitives]
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-finality-grandpa'
rev = '3e651110aa06aa835790df63410a29676243fc54'
version = '2.0.0'

[dependencies.runtime]
package = 'node-runtime'
path = 'runtime'
version = '2.0.0'

[dependencies.sc-basic-authority]
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.sc-cli]
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'
version = '2.0.0'

[dependencies.sc-client]
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'
version = '2.0.0'

[dependencies.sc-consensus-aura]
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'
version = '0.8'

[dependencies.sc-executor]
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'
version = '2.0.0'

[dependencies.sc-network]
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'
version = '0.8'

[dependencies.sc-service]
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'
version = '2.0.0'

[dependencies.sc-transaction-pool]
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'
version = '2.0.0'

[dependencies.sp-consensus]
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'
version = '0.8'

[dependencies.sp-consensus-aura]
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'
version = '0.8'

[dependencies.sp-core]
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'
version = '2.0.0'

[dependencies.sp-inherents]
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'
version = '2.0.0'

[dependencies.sp-io]
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'
version = '2.0.0'

[dependencies.sp-runtime]
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'
version = '2.0.0'

[dependencies.sp-transaction-pool]
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'
version = '2.0.0'

[workspace]
members = [
    'runtime',
    'packages/roaming/roaming-operators',
    'packages/roaming/roaming-networks',
    'packages/roaming/roaming-organizations',
    'packages/roaming/roaming-network-servers',
    'packages/roaming/roaming-devices',
    'packages/roaming/roaming-routing-profiles',
    'packages/roaming/roaming-service-profiles',
    'packages/roaming/roaming-accounting-policies',
    'packages/roaming/roaming-agreement-policies',
    'packages/roaming/roaming-network-profiles',
    'packages/roaming/roaming-device-profiles',
    'packages/roaming/roaming-sessions',
    'packages/roaming/roaming-billing-policies',
    'packages/roaming/roaming-charging-policies',
    'packages/roaming/roaming-packet-bundles',
    'packages/mining/mining-speed-boosts/configuration/token-mining',
    'packages/mining/mining-speed-boosts/configuration/hardware-mining',
    'packages/mining/mining-speed-boosts/rates/token-mining',
    'packages/mining/mining-speed-boosts/rates/hardware-mining',
    'packages/mining/mining-speed-boosts/sampling/token-mining',
    'packages/mining/mining-speed-boosts/sampling/hardware-mining',
    'packages/mining/mining-speed-boosts/eligibility/token-mining',
    'packages/mining/mining-speed-boosts/eligibility/hardware-mining',
    'packages/mining/mining-speed-boosts/claims/token-mining',
    'packages/mining/mining-speed-boosts/claims/hardware-mining',
]

[[bin]]
name = 'node'
path = 'src/main.rs'
