version: "3"

services:
  node-1:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: dhxdocker/datahighway:latest
    ports:
      - 30336:30333
      - 9947:9944
      - 9936:9933
    volumes:
      - ./scripts:/dhx/scripts
    restart: always
    entrypoint:
      - ./docker-entrypoint-node-1.sh
  node-2:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: dhxdocker/datahighway:latest
    ports:
      - 30337:30333
      - 9948:9944
      - 9937:9933
    volumes:
      - ./scripts:/dhx/scripts
    restart: always
    entrypoint:
      - ./docker-entrypoint-node-2.sh
  node-3:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: dhxdocker/datahighway:latest
    ports:
      - 30338:30333
      - 9949:9944
      - 9938:9933
    volumes:
      - ./scripts:/dhx/scripts
    restart: always
    entrypoint:
      - ./docker-entrypoint-node-3.sh
