version: "3"

services:
  emiel:
    image: dhxdocker/datahighway:latest
    ports:
      - 30333:30333
      - 9944:9944
      - 9933:9933
    volumes:
      - ./scripts:/dhx/scripts
    restart: always
    entrypoint:
      - ./docker-entrypoint-emiel.sh
