version: "3"

services:
  alice:
    # Note: Use `dhxdocker/datahighway:latest` from Docker Hub, which
    # reflects the latest version on Github
    image: dhxdocker/datahighway:latest
    env_file:
      - .env
    ports:
      - 30333:30333 # TCP
      - 9944:9944 # WS
      - 9933:9933 # RPC
    volumes:
      - basePath:/tmp
      - ./scripts:/dhx/scripts
    restart: always
    entrypoint:
      - ./docker-entrypoint-alice.sh
  bob:
    image: dhxdocker/datahighway:latest
    env_file:
      - .env
    ports:
      - 30334:30333
      - 9945:9944
      - 9934:9933
    volumes:
      - basePath:/tmp
      - ./scripts:/dhx/scripts
    restart: always
    entrypoint:
      - ./docker-entrypoint-bob.sh
  charlie:
    image: dhxdocker/datahighway:latest
    env_file:
      - .env
    ports:
      - 30335:30333
      - 9946:9944
      - 9935:9933
    volumes:
      - basePath:/tmp
      - ./scripts:/dhx/scripts
    restart: always
    entrypoint:
      - ./docker-entrypoint-charlie.sh
volumes:
  basePath:
