version: "3"

services:
  emiel:
    build: .
    image: dhxdocker/datahighway:latest
    # depends_on:
    #   - bob
    ports:
      - 30333:30333
      - 30336:30336
      - 9947:9947
      - 9934:9934
    volumes:
      - ./scripts:/dhx/scripts
    restart: always
    entrypoint:
      - ./docker-entrypoint-emiel.sh
