version: "3"

services:
  node-1:
    # image: dhxdocker/datahighway:latest
    build:
      context: .
    ports:
      - 30336:30333
      - 9947:9944
      - 9936:9933
    volumes:
      - ./scripts:/usr/src/datahighway-dhx/scripts
    restart: always
    # entrypoint:
    #   - ./docker-entrypoint-node-1.sh

