version: "3"

services:
  node-1:
    build: .
    # image: dhxdocker/datahighway:lukemmd1309A
    env_file:
      - .env
    ports:
      - 30333:30333
      - 9944:9944
      - 9933:9933
    volumes:
      - ./scripts:/dhx/node/scripts
    restart: always
    entrypoint:
      - ./docker-entrypoint-node-1.sh
  node-2:
    build: .
    # image: dhxdocker/datahighway:lukemmd1309A
    env_file:
      - .env
    ports:
      - 30334:30333
      - 9945:9944
      - 9934:9933
    volumes:
      - ./scripts:/dhx/node/scripts
    restart: always
    entrypoint:
      - ./docker-entrypoint-node-2.sh
  node-3:
    build: .
    # image: dhxdocker/datahighway:lukemmd1309A
    env_file:
      - .env
    ports:
      - 30335:30333
      - 9946:9944
      - 9935:9933
    volumes:
      - ./scripts:/dhx/node/scripts
    restart: always
    entrypoint:
      - ./docker-entrypoint-node-3.sh
  node-4:
    build: .
    # image: dhxdocker/datahighway:lukemmd1309A
    env_file:
      - .env
    ports:
      - 30336:30333
      - 9947:9944
      - 9936:9933
    volumes:
      - ./scripts:/dhx/node/scripts
    restart: always
    entrypoint:
      - ./docker-entrypoint-node-4.sh
  node-5:
    build: .
    # image: dhxdocker/datahighway:lukemmd1309A
    env_file:
      - .env
    ports:
      - 30337:30333
      - 9948:9944
      - 9937:9933
    volumes:
      - ./scripts:/dhx/node/scripts
    restart: always
    entrypoint:
      - ./docker-entrypoint-node-5.sh
