[package]
authors = ['MXC Foundation GmbH <https://t.me/mxcfoundation>']
edition = '2018'
name = 'datahighway-runtime'
version = '0.1.0'
build = 'build.rs'
license = 'Apache-2.0'
homepage = 'https://datahighway.com'
repository = 'https://github.com/DataHighway-DHX/node/'

[features]
default = ['std']
std = [
    'codec/std',
    'frame-system/std',
    'frame-system-rpc-runtime-api/std',
    'frame-executive/std',
    'frame-support/std',
    'frame-benchmarking/std',
    'module-primitives/std',
    'pallet-balances/std',
    'pallet-babe/std',
    'pallet-grandpa/std',
    'pallet-indices/std',
    'pallet-collective/std',
    'pallet-membership/std',
    'pallet-treasury/std',
	'pallet-utility/std',
	'pallet-offences/std',
	'pallet-multisig/std',
    'pallet-randomness-collective-flip/std',
    'pallet-staking/std',
    'pallet-sudo/std',
    'pallet-timestamp/std',
    'pallet-transaction-payment/std',
    'pallet-transaction-payment-rpc-runtime-api/std',
    'serde',
    'sp-api/std',
    'sp-block-builder/std',
    'sp-consensus-babe/std',
    'sp-core/std',
    'sp-inherents/std',
    'sp-io/std',
    'sp-offchain/std',
    'sp-runtime/std',
    'sp-session/std',
    'sp-std/std',
    'sp-arithmetic/std',
    'sp-transaction-pool/std',
    'sp-version/std',
    'roaming-operators/std',
    'roaming-networks/std',
    'roaming-organizations/std',
    'roaming-network-servers/std',
    'roaming-devices/std',
    'roaming-routing-profiles/std',
    'roaming-service-profiles/std',
    'roaming-accounting-policies/std',
    'roaming-agreement-policies/std',
    'roaming-network-profiles/std',
    'roaming-device-profiles/std',
    'roaming-sessions/std',
    'roaming-billing-policies/std',
    'roaming-charging-policies/std',
    'roaming-packet-bundles/std',
    'mining-speed-boosts-configuration-token-mining/std',
    'mining-speed-boosts-configuration-hardware-mining/std',
    'mining-speed-boosts-rates-token-mining/std',
    'mining-speed-boosts-rates-hardware-mining/std',
    'mining-speed-boosts-sampling-token-mining/std',
    'mining-speed-boosts-sampling-hardware-mining/std',
    'mining-speed-boosts-eligibility-token-mining/std',
    'mining-speed-boosts-eligibility-hardware-mining/std',
    'mining-speed-boosts-lodgements-token-mining/std',
    'mining-speed-boosts-lodgements-hardware-mining/std',
]

runtime-benchmarks = [
	'sp-runtime/runtime-benchmarks',
	'frame-benchmarking',
	'frame-system/runtime-benchmarks',
	'frame-support/runtime-benchmarks',
	'pallet-collective/runtime-benchmarks',
]

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]

# third-party dependencies
codec = { version = '1.3.1', package = 'parity-scale-codec', default-features = false, features = ['derive'] }
integer-sqrt = { version = '0.1.2' }
serde = { version = '1.0.102', optional = true, features = ['derive'] }
static_assertions = '1.1.0'
hex-literal = { version = '0.2.1', optional = true }
smallvec = '1.4.0'

frame-executive = { version = '2.0.0-rc4', default-features = false }
frame-support = { version = '2.0.0-rc4', default-features = false }
frame-system = { version = '2.0.0-rc4', default-features = false }
frame-system-rpc-runtime-api = { version = '2.0.0-rc4', default-features = false }
frame-benchmarking = { version = '2.0.0-rc4', default-features = false, optional = true }
pallet-balances = { version = '2.0.0-rc4', default-features = false }
pallet-babe = { version = '2.0.0-rc4', default-features = false }
pallet-collective = { version = '2.0.0-rc4', default-features = false }
pallet-grandpa = { version = '2.0.0-rc4', default-features = false }
pallet-indices = { version = '2.0.0-rc4', default-features = false }
pallet-membership = { version = '2.0.0-rc4', default-features = false }
pallet-randomness-collective-flip = { version = '2.0.0-rc4', default-features = false }
pallet-session = { version = '2.0.0-rc4', default-features = false }
pallet-staking = { version = '2.0.0-rc4', default-features = false }
pallet-staking-reward-curve = { version = '2.0.0-rc4', default-features = false }
pallet-sudo = { version = '2.0.0-rc4', default-features = false }
pallet-timestamp = { version = '2.0.0-rc4', default-features = false }
pallet-transaction-payment = { version = '2.0.0-rc4', default-features = false }
pallet-transaction-payment-rpc-runtime-api = { version = '2.0.0-rc4', default-features = false }
pallet-treasury = { version = '2.0.0-rc4', default-features = false }
pallet-utility = { version = '2.0.0-rc4', default-features = false }
pallet-offences = { version = '2.0.0-rc4', default-features = false }
pallet-multisig = { version = '2.0.0-rc4', default-features = false }
sp-api = { version = '2.0.0-rc4', default-features = false }
sp-block-builder = { version = '2.0.0-rc4', default-features = false }
sp-consensus-babe = { version = '0.8.0-rc4', default-features = false }
sp-core = { version = '2.0.0-rc4', default-features = false }
sp-inherents = { version = '2.0.0-rc4', default-features = false }
sp-io = { version = '2.0.0-rc4', default-features = false }
sp-offchain = { version = '2.0.0-rc4', default-features = false }
sp-runtime = { version = '2.0.0-rc4', default-features = false }
sp-session = { version = '2.0.0-rc4', default-features = false }
sp-staking = { version = '2.0.0-rc4', default-features = false }
sp-std = { version = '2.0.0-rc4', default-features = false }
sp-arithmetic = { version = '2.0.0-rc4', default-features = false }
sp-transaction-pool = { version = '2.0.0-rc4', default-features = false }
sp-version = { version = '2.0.0-rc4', default-features = false }
sp-application-crypto = { version = '2.0.0-rc4', default-features = false }

# env = { version = '0.1.0', default_features = false, package = 'env', path = '../pallets/env'}
roaming-operators = { default_features = false, package = 'roaming-operators', path = '../pallets/roaming/roaming-operators' }
roaming-networks = { default_features = false, package = 'roaming-networks', path = '../pallets/roaming/roaming-networks' }
roaming-organizations = { default_features = false, package = 'roaming-organizations', path = '../pallets/roaming/roaming-organizations' }
roaming-network-servers = { default_features = false, package = 'roaming-network-servers', path = '../pallets/roaming/roaming-network-servers' }
roaming-devices = { default_features = false, package = 'roaming-devices', path = '../pallets/roaming/roaming-devices' }
roaming-routing-profiles = { default_features = false, package = 'roaming-routing-profiles', path = '../pallets/roaming/roaming-routing-profiles' }
roaming-service-profiles = { default_features = false, package = 'roaming-service-profiles', path = '../pallets/roaming/roaming-service-profiles' }
roaming-accounting-policies = { default_features = false, package = 'roaming-accounting-policies', path = '../pallets/roaming/roaming-accounting-policies' }
roaming-agreement-policies = { default_features = false, package = 'roaming-agreement-policies', path = '../pallets/roaming/roaming-agreement-policies' }
roaming-network-profiles = { default_features = false, package = 'roaming-network-profiles', path = '../pallets/roaming/roaming-network-profiles' }
roaming-device-profiles = { default_features = false, package = 'roaming-device-profiles', path = '../pallets/roaming/roaming-device-profiles' }
roaming-sessions = { default_features = false, package = 'roaming-sessions', path = '../pallets/roaming/roaming-sessions' }
roaming-billing-policies = { default_features = false, package = 'roaming-billing-policies', path = '../pallets/roaming/roaming-billing-policies' }
roaming-charging-policies = { default_features = false, package = 'roaming-charging-policies', path = '../pallets/roaming/roaming-charging-policies' }
roaming-packet-bundles = { default_features = false, package = 'roaming-packet-bundles', path = '../pallets/roaming/roaming-packet-bundles' }
mining-speed-boosts-configuration-token-mining = { default_features = false, package = 'mining-speed-boosts-configuration-token-mining', path = '../pallets/mining/mining-speed-boosts/configuration/token-mining' }
mining-speed-boosts-configuration-hardware-mining = { default_features = false, package = 'mining-speed-boosts-configuration-hardware-mining', path = '../pallets/mining/mining-speed-boosts/configuration/hardware-mining' }
mining-speed-boosts-rates-token-mining = { default_features = false, package = 'mining-speed-boosts-rates-token-mining', path = '../pallets/mining/mining-speed-boosts/rates/token-mining' }
mining-speed-boosts-rates-hardware-mining = { default_features = false, package = 'mining-speed-boosts-rates-hardware-mining', path = '../pallets/mining/mining-speed-boosts/rates/hardware-mining' }
mining-speed-boosts-sampling-token-mining = { default_features = false, package = 'mining-speed-boosts-sampling-token-mining', path = '../pallets/mining/mining-speed-boosts/sampling/token-mining' }
mining-speed-boosts-sampling-hardware-mining = { default_features = false, package = 'mining-speed-boosts-sampling-hardware-mining', path = '../pallets/mining/mining-speed-boosts/sampling/hardware-mining' }
mining-speed-boosts-eligibility-token-mining = { default_features = false, package = 'mining-speed-boosts-eligibility-token-mining', path = '../pallets/mining/mining-speed-boosts/eligibility/token-mining' }
mining-speed-boosts-eligibility-hardware-mining = { default_features = false, package = 'mining-speed-boosts-eligibility-hardware-mining', path = '../pallets/mining/mining-speed-boosts/eligibility/hardware-mining' }
mining-speed-boosts-lodgements-token-mining = { default_features = false, package = 'mining-speed-boosts-lodgements-token-mining', path = '../pallets/mining/mining-speed-boosts/lodgements/token-mining' }
mining-speed-boosts-lodgements-hardware-mining = { default_features = false, package = 'mining-speed-boosts-lodgements-hardware-mining', path = '../pallets/mining/mining-speed-boosts/lodgements/hardware-mining' }
module-primitives = { default-features = false, path = '../pallets/primitives' }

[build-dependencies]
wasm-builder-runner = { version = '1.0.6', package = 'substrate-wasm-builder-runner' }
