[package]
authors = ['MXC Foundation GmbH <https://t.me/mxcfoundation>', 'Luke Schoen <luke@mxc.org>', 'Ilya Beregovskiy <ilya@mxc.org>']
edition = '2018'
name = 'datahighway-runtime'
version = '3.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }

# Substrate dependencies
frame-executive = { default-features = false, version = '3.0.0' }
frame-support = { default-features = false, version = '3.0.0' }
frame-system = { default-features = false, version = '3.0.0' }
pallet-babe = { default-features = false, version = '3.0.0' }
pallet-balances = { default-features = false, version = '3.0.0' }
pallet-grandpa = { default-features = false, version = '3.0.0' }
pallet-randomness-collective-flip = { default-features = false, version = '3.0.0' }
pallet-sudo = { default-features = false, version = '3.0.0' }
pallet-timestamp = { default-features = false, version = '3.0.0' }
pallet-transaction-payment = { default-features = false, version = '3.0.0' }
sp-api = { default-features = false, version = '3.0.0' }
sp-block-builder = { default-features = false, version = '3.0.0' }
sp-consensus-babe = { default-features = false, version = '0.9.0' }
sp-core = { default-features = false, version = '3.0.0' }
sp-inherents = { default-features = false, version = '3.0.0' }
sp-io = { default-features = false, version = '3.0.0' }
sp-offchain = { default-features = false, version = '3.0.0' }
sp-runtime = { default-features = false, version = '3.0.0' }
sp-session = { default-features = false, version = '3.0.0' }
sp-staking = { default-features = false, version = '3.0.0' }
sp-std = { default-features = false, version = '3.0.0' }
sp-transaction-pool = { default-features = false, version = '3.0.0' }
sp-version = { default-features = false, version = '3.0.0' }
pallet-collective = { default-features = false, version = '3.0.0' }
pallet-indices = { default-features = false, version = '3.0.0' }
pallet-membership = { default-features = false, version = '3.0.0' }
pallet-session = { default-features = false, version = '3.0.0' }
pallet-staking = { default-features = false, version = '3.0.0' }
pallet-staking-reward-curve = { default-features = false, version = '3.0.0' }
pallet-treasury = { default-features = false, version = '3.0.0' }

# Used for the node template's RPCs
frame-system-rpc-runtime-api = { default-features = false, version = '3.0.0' }
pallet-transaction-payment-rpc-runtime-api = { default-features = false, version = '3.0.0' }

# Used for runtime benchmarking
frame-benchmarking = { default-features = false, optional = true, version = '3.1.0' }
frame-system-benchmarking = { default-features = false, optional = true, version = '3.0.0' }
hex-literal = { optional = true, version = '0.3.1' }

# Other
serde = { features = ['derive'], optional = true, version = '1.0.119' }

# Local dependencies
# env = { version = '1.0.0', default_features = false, package = 'env', path = '../pallets/env'}
roaming-operators = { default_features = false, package = 'roaming-operators', path = '../pallets/roaming/roaming-operators' }
roaming-networks = { default_features = false, package = 'roaming-networks', path = '../pallets/roaming/roaming-networks' }
roaming-organizations = { default_features = false, package = 'roaming-organizations', path = '../pallets/roaming/roaming-organizations' }
roaming-network-servers = { default_features = false, package = 'roaming-network-servers', path = '../pallets/roaming/roaming-network-servers' }
roaming-devices = { default_features = false, package = 'roaming-devices', path = '../pallets/roaming/roaming-devices' }
roaming-routing-profiles = { default_features = false, package = 'roaming-routing-profiles', path = '../pallets/roaming/roaming-routing-profiles' }
roaming-service-profiles = { default_features = false, package = 'roaming-service-profiles', path = '../pallets/roaming/roaming-service-profiles' }
roaming-accounting-policies = { default_features = false, package = 'roaming-accounting-policies', path = '../pallets/roaming/roaming-accounting-policies' }
roaming-agreement-policies = { default_features = false, package = 'roaming-agreement-policies', path = '../pallets/roaming/roaming-agreement-policies' }
roaming-network-profiles = { default_features = false, package = 'roaming-network-profiles', path = '../pallets/roaming/roaming-network-profiles' }
roaming-device-profiles = { default_features = false, package = 'roaming-device-profiles', path = '../pallets/roaming/roaming-device-profiles' }
roaming-sessions = { default_features = false, package = 'roaming-sessions', path = '../pallets/roaming/roaming-sessions' }
roaming-billing-policies = { default_features = false, package = 'roaming-billing-policies', path = '../pallets/roaming/roaming-billing-policies' }
roaming-charging-policies = { default_features = false, package = 'roaming-charging-policies', path = '../pallets/roaming/roaming-charging-policies' }
roaming-packet-bundles = { default_features = false, package = 'roaming-packet-bundles', path = '../pallets/roaming/roaming-packet-bundles' }
mining-config-token = { default_features = false, package = 'mining-config-token', path = '../pallets/mining/config/token' }
mining-config-hardware = { default_features = false, package = 'mining-config-hardware', path = '../pallets/mining/config/hardware' }
mining-rates-token = { default_features = false, package = 'mining-rates-token', path = '../pallets/mining/rates/token' }
mining-rates-hardware = { default_features = false, package = 'mining-rates-hardware', path = '../pallets/mining/rates/hardware' }
mining-sampling-token = { default_features = false, package = 'mining-sampling-token', path = '../pallets/mining/sampling/token' }
mining-sampling-hardware = { default_features = false, package = 'mining-sampling-hardware', path = '../pallets/mining/sampling/hardware' }
mining-eligibility-token = { default_features = false, package = 'mining-eligibility-token', path = '../pallets/mining/eligibility/token' }
mining-eligibility-hardware = { default_features = false, package = 'mining-eligibility-hardware', path = '../pallets/mining/eligibility/hardware' }
mining-claims-token = { default_features = false, package = 'mining-claims-token', path = '../pallets/mining/claims/token' }
mining-claims-hardware = { default_features = false, package = 'mining-claims-hardware', path = '../pallets/mining/claims/hardware' }
mining-execution-token = { default_features = false, package = 'mining-execution-token', path = '../pallets/mining/execution/token' }
exchange-rate = { default_features = false, package = 'exchange-rate', path = '../pallets/exchange-rate' }
module-primitives = { default-features = false, path = '../pallets/primitives' }

[build-dependencies]
substrate-wasm-builder = '4.0.0'

[features]
default = ['std']
std = [
    'codec/std',
    'frame-system-rpc-runtime-api/std',
    'frame-executive/std',
    'frame-support/std',
    'frame-system/std',
    'module-primitives/std',
    'pallet-balances/std',
    'pallet-babe/std',
    'pallet-grandpa/std',
    'pallet-indices/std',
    'pallet-collective/std',
    'pallet-membership/std',
    'pallet-treasury/std',
    'pallet-randomness-collective-flip/std',
    'pallet-staking/std',
    'pallet-sudo/std',
    'pallet-timestamp/std',
    'pallet-transaction-payment/std',
    'pallet-transaction-payment-rpc-runtime-api/std',
    'serde',
    'sp-api/std',
    'sp-block-builder/std',
    'sp-consensus-babe/std',
    'sp-core/std',
    'sp-inherents/std',
    'sp-io/std',
    'sp-offchain/std',
    'sp-runtime/std',
    'sp-session/std',
    'sp-std/std',
    'sp-transaction-pool/std',
    'sp-version/std',
    'roaming-operators/std',
    'roaming-networks/std',
    'roaming-organizations/std',
    'roaming-network-servers/std',
    'roaming-devices/std',
    'roaming-routing-profiles/std',
    'roaming-service-profiles/std',
    'roaming-accounting-policies/std',
    'roaming-agreement-policies/std',
    'roaming-network-profiles/std',
    'roaming-device-profiles/std',
    'roaming-sessions/std',
    'roaming-billing-policies/std',
    'roaming-charging-policies/std',
    'roaming-packet-bundles/std',
    'mining-config-token/std',
    'mining-config-hardware/std',
    'mining-rates-token/std',
    'mining-rates-hardware/std',
    'mining-sampling-token/std',
    'mining-sampling-hardware/std',
    'mining-eligibility-token/std',
    'mining-eligibility-hardware/std',
    'mining-claims-token/std',
    'mining-claims-hardware/std',
    'mining-execution-token/std',
    'exchange-rate/std',
]
runtime-benchmarks = [
    'hex-literal',
    'frame-benchmarking',
    'frame-support/runtime-benchmarks',
    'frame-system-benchmarking',
    'frame-system/runtime-benchmarks',
    'pallet-balances/runtime-benchmarks',
    'pallet-timestamp/runtime-benchmarks',
    'sp-runtime/runtime-benchmarks',
]
