[package]
authors = ['MXC Foundation GmbH <https://t.me/mxcfoundation>']
edition = '2018'
name = 'datahighway-runtime'
version = '0.1.0'

[features]
default = ['std']
std = [
    'pallet-balances/std',
    'pallet-babe/std',
    'codec/std',
    'frame-executive/std',
    'frame-support/std',
    'module-primitives/std',
    'pallet-grandpa/std',
    'pallet-indices/std',
    'pallet-collective/std',
    'pallet-membership/std',
    'pallet-treasury/std',
    'pallet-staking/std',
    'pallet-randomness-collective-flip/std',
    'serde',
    'sp-api/std',
    'sp-block-builder/std',
    'sp-consensus-babe/std',
    'sp-core/std',
    'sp-inherents/std',
    'sp-io/std',
    'sp-offchain/std',
    'sp-runtime/std',
    'sp-session/std',
    'sp-std/std',
    'sp-transaction-pool/std',
    'sp-version/std',
    'pallet-sudo/std',
    'system/std',
    'system-rpc-runtime-api/std',
    'pallet-timestamp/std',
    'pallet-transaction-payment/std',
    'pallet-transaction-payment-rpc-runtime-api/std',
    'roaming-operators/std',
    'roaming-networks/std',
    'roaming-organizations/std',
    'roaming-network-servers/std',
    'roaming-devices/std',
    'roaming-routing-profiles/std',
    'roaming-service-profiles/std',
    'roaming-accounting-policies/std',
    'roaming-agreement-policies/std',
    'roaming-network-profiles/std',
    'roaming-device-profiles/std',
    'roaming-sessions/std',
    'roaming-billing-policies/std',
    'roaming-charging-policies/std',
    'roaming-packet-bundles/std',
    'mining-speed-boosts-configuration-token-mining/std',
    'mining-speed-boosts-configuration-hardware-mining/std',
    'mining-speed-boosts-rates-token-mining/std',
    'mining-speed-boosts-rates-hardware-mining/std',
    'mining-speed-boosts-sampling-token-mining/std',
    'mining-speed-boosts-sampling-hardware-mining/std',
    'mining-speed-boosts-eligibility-token-mining/std',
    'mining-speed-boosts-eligibility-hardware-mining/std',
    'mining-speed-boosts-claims-token-mining/std',
    'mining-speed-boosts-claims-hardware-mining/std',
]

[dependencies]
codec = { version = '1.0.0', package = 'parity-scale-codec', default-features = false, features = ['derive'] }

pallet-balances = { version = '2.0.0-alpha.3', default-features = false, package = 'pallet-balances', rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
frame-executive = { version = '2.0.0-alpha.3', default-features = false, rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
frame-support = { version = '2.0.0-alpha.3', default-features = false, rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
system-rpc-runtime-api = { version = '2.0.0-alpha.3', package = 'frame-system-rpc-runtime-api', default-features = false, rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
pallet-grandpa = { version = '2.0.0-alpha.3', default-features = false, package = 'pallet-grandpa', rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
pallet-indices = { version = '2.0.0-alpha.3', default-features = false, package = 'pallet-indices', rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
pallet-randomness-collective-flip = { version = '2.0.0-alpha.3', default-features = false, package = 'pallet-randomness-collective-flip', rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
serde = { version = '1.0.101', optional = true, features = ['derive'] }
sp-api = { version = '2.0.0-alpha.3', default-features = false, rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
sp-block-builder = { default-features = false, rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
sp-consensus-babe = { version = '0.8.0-alpha.3', default-features = false, rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
sp-core = { version = '2.0.0-alpha.3', default-features = false, rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
sp-inherents = { version = '2.0.0-alpha.3', default-features = false, rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
sp-io = { version = '2.0.0-alpha.3', default-features = false, rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
sp-offchain = { version = '2.0.0-alpha.3', default-features = false, rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
sp-runtime = { version = '2.0.0-alpha.3', default-features = false, rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
sp-session = { version = '2.0.0-alpha.3', default-features = false, rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
sp-staking = { version = '2.0.0-alpha.3', default-features = false, rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
sp-std = { version = '2.0.0-alpha.3', default-features = false, rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
sp-transaction-pool = { version = '2.0.0-alpha.3', default-features = false, rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
sp-version = { version = '2.0.0-alpha.3', default-features = false, rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
pallet-sudo = { version = '2.0.0-alpha.3', default-features = false, package = 'pallet-sudo', rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
system = { version = '2.0.0-alpha.3', default-features = false, package = 'frame-system', rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
pallet-timestamp = { version = '2.0.0-alpha.3', default-features = false, package = 'pallet-timestamp', rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
pallet-transaction-payment = { version = '2.0.0-alpha.3', default-features = false, package = 'pallet-transaction-payment', rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
pallet-transaction-payment-rpc-runtime-api = { version = '2.0.0-alpha.3', default-features = false, package = 'pallet-transaction-payment-rpc-runtime-api', rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
pallet-collective = { version = '2.0.0-alpha.3', default-features = false, package = 'pallet-collective', rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
pallet-membership = { version = '2.0.0-alpha.3', default-features = false, package = 'pallet-membership', rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
pallet-treasury = { version = '2.0.0-alpha.3', default-features = false, package = 'pallet-treasury', rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
pallet-staking = { version = '2.0.0-alpha.3', default-features = false, package = 'pallet-staking', rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
pallet-staking-reward-curve = { version = '2.0.0-alpha.3', default-features = false, package = 'pallet-staking-reward-curve', rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
pallet-session = { version = '2.0.0-alpha.3', default-features = false, package = 'pallet-session', rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
pallet-babe = { version = '2.0.0-alpha.3', default-features = false, package = 'pallet-babe', rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }

# env = { version = '0.1.0', default_features = false, package = 'env', path = '../pallets/env'}
roaming-operators = { default_features = false, package = 'roaming-operators', path = '../pallets/roaming/roaming-operators' }
roaming-networks = { default_features = false, package = 'roaming-networks', path = '../pallets/roaming/roaming-networks' }
roaming-organizations = { default_features = false, package = 'roaming-organizations', path = '../pallets/roaming/roaming-organizations' }
roaming-network-servers = { default_features = false, package = 'roaming-network-servers', path = '../pallets/roaming/roaming-network-servers' }
roaming-devices = { default_features = false, package = 'roaming-devices', path = '../pallets/roaming/roaming-devices' }
roaming-routing-profiles = { default_features = false, package = 'roaming-routing-profiles', path = '../pallets/roaming/roaming-routing-profiles' }
roaming-service-profiles = { default_features = false, package = 'roaming-service-profiles', path = '../pallets/roaming/roaming-service-profiles' }
roaming-accounting-policies = { default_features = false, package = 'roaming-accounting-policies', path = '../pallets/roaming/roaming-accounting-policies' }
roaming-agreement-policies = { default_features = false, package = 'roaming-agreement-policies', path = '../pallets/roaming/roaming-agreement-policies' }
roaming-network-profiles = { default_features = false, package = 'roaming-network-profiles', path = '../pallets/roaming/roaming-network-profiles' }
roaming-device-profiles = { default_features = false, package = 'roaming-device-profiles', path = '../pallets/roaming/roaming-device-profiles' }
roaming-sessions = { default_features = false, package = 'roaming-sessions', path = '../pallets/roaming/roaming-sessions' }
roaming-billing-policies = { default_features = false, package = 'roaming-billing-policies', path = '../pallets/roaming/roaming-billing-policies' }
roaming-charging-policies = { default_features = false, package = 'roaming-charging-policies', path = '../pallets/roaming/roaming-charging-policies' }
roaming-packet-bundles = { default_features = false, package = 'roaming-packet-bundles', path = '../pallets/roaming/roaming-packet-bundles' }
mining-speed-boosts-configuration-token-mining = { default_features = false, package = 'mining-speed-boosts-configuration-token-mining', path = '../pallets/mining/mining-speed-boosts/configuration/token-mining' }
mining-speed-boosts-configuration-hardware-mining = { default_features = false, package = 'mining-speed-boosts-configuration-hardware-mining', path = '../pallets/mining/mining-speed-boosts/configuration/hardware-mining' }
mining-speed-boosts-rates-token-mining = { default_features = false, package = 'mining-speed-boosts-rates-token-mining', path = '../pallets/mining/mining-speed-boosts/rates/token-mining' }
mining-speed-boosts-rates-hardware-mining = { default_features = false, package = 'mining-speed-boosts-rates-hardware-mining', path = '../pallets/mining/mining-speed-boosts/rates/hardware-mining' }
mining-speed-boosts-sampling-token-mining = { default_features = false, package = 'mining-speed-boosts-sampling-token-mining', path = '../pallets/mining/mining-speed-boosts/sampling/token-mining' }
mining-speed-boosts-sampling-hardware-mining = { default_features = false, package = 'mining-speed-boosts-sampling-hardware-mining', path = '../pallets/mining/mining-speed-boosts/sampling/hardware-mining' }
mining-speed-boosts-eligibility-token-mining = { default_features = false, package = 'mining-speed-boosts-eligibility-token-mining', path = '../pallets/mining/mining-speed-boosts/eligibility/token-mining' }
mining-speed-boosts-eligibility-hardware-mining = { default_features = false, package = 'mining-speed-boosts-eligibility-hardware-mining', path = '../pallets/mining/mining-speed-boosts/eligibility/hardware-mining' }
mining-speed-boosts-claims-token-mining = { default_features = false, package = 'mining-speed-boosts-claims-token-mining', path = '../pallets/mining/mining-speed-boosts/claims/token-mining' }
mining-speed-boosts-claims-hardware-mining = { default_features = false, package = 'mining-speed-boosts-claims-hardware-mining', path = '../pallets/mining/mining-speed-boosts/claims/hardware-mining' }
module-primitives = { default-features = false, path = '../pallets/primitives' }

[build-dependencies]
wasm-builder-runner = { version = '1.0.4', package = 'substrate-wasm-builder-runner', rev = '65ad8e9632f1a627fc9fb386dc5b60a54741d7a0', git = 'https://github.com/paritytech/substrate.git' }
