[package]
name = "roaming-network-servers"
version = "0.1.0"
authors = ["Luke Schoen"]
edition = "2018"

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'randomness-collective-flip/std',
    'sp-io/std',
    'sp-std/std',
    'system/std',
    'transaction-payment/std',
    'log/std',
    'serde',
    'roaming-networks/std',
    'roaming-operators/std',
]

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.0.0'

[dependencies.frame-support]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-support'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.randomness-collective-flip]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-randomness-collective-flip'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.sp-io]
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'
version = '2.0.0'

[dependencies.sp-std]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-std'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.system]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-system'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.transaction-payment]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-transaction-payment'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dev-dependencies.balances]
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-balances'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.roaming-networks]
default_features = false
package = 'roaming-networks'
path = '../roaming-networks'

[dependencies.roaming-operators]
default_features = false
package = 'roaming-operators'
path = '../roaming-operators'

[dependencies.log]
version = "0.4.8"

[dependencies.serde]
version = "1.0"
optional = true
