version: 2.1

orbs:
  rust: glotrade/rust@0.1.3

jobs:
  build:
    docker:
      - image: 'rust:1'

    environment:
      RUSTFLAGS: "-W unused-extern-crates"
      RUST_TOOLCHAIN_STABLE: stable
      RUST_TOOLCHAIN_NIGHTLY: nightly 

    steps:
      - checkout
      - run:
          name: Check code formatting
          command: |
            apt-get -y update
            apt-get install -y cmake pkg-config libssl-dev libsecp256k1-dev
            rustup toolchain install $RUST_TOOLCHAIN_STABLE
            rustup toolchain install $RUST_TOOLCHAIN_NIGHTLY
            rustup target add wasm32-unknown-unknown --toolchain nightly
            rustup component add rustfmt
            rustup set profile default
            rustup update
            cargo update
            cargo fmt -- --check || true
      - run:
          name: Run integration test
          command: |
            apt-get -y update
            apt-get install -y cmake pkg-config libssl-dev libsecp256k1-dev
            rustup toolchain install $RUST_TOOLCHAIN_STABLE
            rustup toolchain install $RUST_TOOLCHAIN_NIGHTLY
            rustup target add wasm32-unknown-unknown --toolchain nightly
            rustup set profile default
            rustup update
            cargo update
            cargo test -p node-runtime
