version: 2.1

orbs:
  rust: glotrade/rust@0.1.3

jobs:
  build:
    docker:
      - image: 'rust:1'

    environment:
      RUSTFLAGS: "-W unused-extern-crates"

    steps:
      - checkout
      - run:
          name: Check formatting
          command: 
            rustup toolchain install $RUST_TOOLCHAIN
            rustup default $RUST_TOOLCHAIN
            rustc --version
            rustup --version
            cargo --version
            cargo fmt -- --check
      - run:
          name: Test
          command: 
            cargo test -p node-runtime