version: 2.1

orbs:
  rust: glotrade/rust@0.1.3

jobs:
  build:
    docker:
      - image: 'rust:1'

    environment:
      RUSTFLAGS: "-W unused-extern-crates"
      RUST_TOOLCHAIN: stable

    steps:
      - checkout
      - run:
          name: Check code formatting
          command: |
            apt-get -y update
            apt-get install -y cmake pkg-config libssl-dev libsecp256k1-dev
            rustup toolchain install $RUST_TOOLCHAIN
            rustup set default default
            rustup update
            cargo update
            cargo fmt -- --check || true
      - run:
          name: Run integration test
          command: |
            apt-get -y update
            apt-get install -y cmake pkg-config libssl-dev libsecp256k1-dev
            rustup toolchain install $RUST_TOOLCHAIN
            rustup set default default
            rustup update
            cargo update
            cargo test -p node-runtime
