version: 2.1

orbs:
  rust: glotrade/rust@0.1.3

jobs:
  build:
    docker:
      - image: 'rust:1'

    environment:
      RUSTFLAGS: "-W unused-extern-crates"
      RUST_TOOLCHAIN: nightly-2019-10-13

    steps:
      - checkout
      - run:
          name: Check code formatting
          command: |
            rustup toolchain install $RUST_TOOLCHAIN
            rustup default $RUST_TOOLCHAIN
            rustup component add rustfmt
            rustc --version
            rustup --version
            cargo --version
            cargo fmt -- --check || true
      - run:
          name: Run integration test
          command: |
            rustup toolchain install $RUST_TOOLCHAIN
            rustup default $RUST_TOOLCHAIN
            rustup component add rustfmt
            cargo test -p node-runtime