[package]
name = "lockdrop"
version = "0.1.0"
authors = ["Ilya Beregovskiy"]
edition = "2018"

[dependencies]
sp-std = { git = 'https://github.com/paritytech/substrate', rev = '283bb60954d6809a76e52619e58c78fb8053e3eb', default-features = false }

[features]
default = ['std']
std = [
    'sp-std/std',
]
