[package]
name = "lockdrop"
version = "0.1.0"
authors = ["Ilya Beregovskiy"]
edition = "2021"

[dependencies]
sp-std = { git = 'https://github.com/paritytech/substrate', rev = '55cd07a7e22c26932f7bd16b87ea5a7569e38eb4', default-features = false }

[features]
default = ['std']
std = [
    'sp-std/std',
]
