[package]
name = "lockdrop"
version = "0.1.0"
authors = ["Ilya Beregovskiy"]
edition = "2018"

[dependencies]
sp-std = { git = 'https://github.com/paritytech/substrate', rev = '904495bc14eff5171fca5912247e772948439411', default-features = false }

[features]
default = ['std']
std = [
    'sp-std/std',
]
