[package]
name = "lockdrop"
version = "0.1.0"
authors = ["Ilya Beregovskiy"]
edition = "2018"

[dependencies]
sp-std = { git = 'https://github.com/paritytech/substrate', rev = 'b7a1a2cda5c860f18a7802051e881c5062828042', default-features = false }

[features]
default = ['std']
std = [
    'sp-std/std',
]
