[package]
name = "lockdrop"
version = "0.1.0"
authors = ["Ilya Beregovskiy"]
edition = "2018"

[dependencies]
sp-std = { git = 'https://github.com/paritytech/substrate', rev = '993907f9deb180795b291ba752b9c204165d74dc', default-features = false }

[features]
default = ['std']
std = [
    'sp-std/std',
]
