[package]
name = "lockdrop"
version = "0.1.0"
authors = ["Ilya Beregovskiy"]
edition = "2018"

[dependencies]
sp-std = { git = 'https://github.com/paritytech/substrate', rev = '6ac86d545f6da8e4afc373dc0876c3e7ba79e51b', default-features = false }

[features]
default = ['std']
std = [
    'sp-std/std',
]
