[package]
name = "lockdrop"
version = "0.1.0"
authors = ["Ilya Beregovskiy"]
edition = "2018"

[dependencies]
sp-std = { git = 'https://github.com/paritytech/substrate', rev = '24613496216b8c991baa24b26afc8346d313fbf5', default-features = false }

[features]
default = ['std']
std = [
    'sp-std/std',
]
