[package]
name = "lockdrop"
version = "0.1.0"
authors = ["Ilya Beregovskiy"]
edition = "2018"

[dependencies]
sp-std = { git = 'https://github.com/paritytech/substrate', rev = 'a8ada8a654a1e50d855345d07f5f8f8cbce0a818', default-features = false }

[features]
default = ['std']
std = [
    'sp-std/std',
]
