[package]
name = "lockdrop"
version = "0.1.0"
authors = ["Ilya Beregovskiy"]
edition = "2018"

[dependencies]
sp-std = { git = 'https://github.com/paritytech/substrate', rev = '56b9d48c92cd2aff9b1da83fe66e45de7860fd97', default-features = false }

[features]
default = ['std']
std = [
    'sp-std/std',
]
