[package]
name = "lockdrop"
version = "0.1.0"
authors = ["Ilya Beregovskiy"]
edition = "2018"

[dependencies]
sp-std = { git = 'https://github.com/paritytech/substrate', rev = 'a2fdd15c047289426e6023f393ee9172d81cc0ff', default-features = false }

[features]
default = ['std']
std = [
    'sp-std/std',
]
