[package]
name = "lockdrop"
version = "0.1.0"
authors = ["Ilya Beregovskiy"]
edition = "2018"

[dependencies]
sp-std = { git = 'https://github.com/paritytech/substrate', rev = 'cc24950837d3a98727b12ba9229f2aabb67f411c', default-features = false }

[features]
default = ['std']
std = [
    'sp-std/std',
]
