[package]
name = "lockdrop"
version = "0.1.0"
authors = ["Ilya Beregovskiy"]
edition = "2018"

[dependencies]
sp-std = { git = 'https://github.com/paritytech/substrate', rev = '8712b36e1391d8351ca75931a507667200cfb61a', default-features = false }

[features]
default = ['std']
std = [
    'sp-std/std',
]
