[package]
name = "lockdrop"
version = "0.1.0"
authors = ["Ilya Beregovskiy"]
edition = "2018"

[dependencies]
sp-std = { git = 'https://github.com/paritytech/substrate', rev = '2e34d473e6ba81b454eb039544f2162975c0b30b', default-features = false }

[features]
default = ['std']
std = [
    'sp-std/std',
]
