[package]
name = "lockdrop"
version = "0.1.0"
authors = ["Ilya Beregovskiy"]
edition = "2021"

[dependencies]
sp-std = { git = 'https://github.com/paritytech/substrate', rev = '36c38fb26b362ee0666d655ad5d6ad7279ba7e07', default-features = false }

[features]
default = ['std']
std = [
    'sp-std/std',
]
