[package]
authors = ['MXC Foundation gGmbH <https://t.me/mxcfoundation>', 'Luke Schoen <luke@mxc.org>', 'Ilya Beregovskiy <ilya@mxc.org>']
build = 'build.rs'
edition = '2018'
name = 'datahighway'
version = '3.0.6'

[[bin]]
name = 'datahighway'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-build-script-utils = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
vergen = '3.0.4'

[dependencies]
codec = { version = '2.3.1', package = 'parity-scale-codec', default-features = false, features = ['derive', 'max-encoded-len'] }
scale-info = { version = '1.0', default-features = false, features = ['derive'] }
jsonrpc-core = '18.0.0'
structopt = '0.3.8'
hex = { version = '0.4.3', default_features = false, features = ['alloc'] }
hex-literal = '0.3.4'
serde = { version = '1.0.102', features = ['derive'] }
serde_json = '1.0.68'

# local node-specific dependencies
datahighway-runtime = { version = '3.0.6', path = '../runtime' }

# Substrate dependencies
frame-benchmarking = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
frame-benchmarking-cli = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
module-primitives = { version = '3.0.6', default-features = false, path = '../pallets/primitives' }
pallet-authority-discovery = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
pallet-democracy = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
pallet-im-online = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
pallet-transaction-payment-rpc = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sc-authority-discovery = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sc-basic-authorship = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sc-cli = { features = ['wasmtime'], git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sc-client-api = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sc-consensus-epochs = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sc-chain-spec = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sc-finality-grandpa = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sc-keystore = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sc-client-db = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sc-consensus = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sc-consensus-aura = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sc-consensus-slots = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sc-executor = { features = ['wasmtime'], git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sc-rpc = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sc-rpc-api = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sc-service = {  git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e', default-features = false, features = ['wasmtime'] }
sc-transaction-pool = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sc-transaction-pool-api = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sp-api = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sp-authority-discovery = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sp-block-builder = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sp-blockchain = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sp-consensus = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sp-consensus-aura = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sp-core = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sp-finality-grandpa = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sp-keystore = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sc-network = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sp-runtime = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sp-timestamp = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sp-authorship = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sp-tracing = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sp-transaction-pool = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sp-transaction-storage-proof = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sc-consensus-uncles = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
sc-telemetry = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }
substrate-frame-rpc-system = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e' }

[dev-dependencies]
futures = { version = '0.3.16' }

[features]
default = []
