[package]
authors = ['MXC Foundation gGmbH <https://t.me/mxcfoundation>', 'Luke Schoen <luke@mxc.org>', 'Ilya Beregovskiy <ilya@mxc.org>']
build = 'build.rs'
edition = '2018'
name = 'datahighway'
version = '3.0.5'

[[bin]]
name = 'datahighway'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-build-script-utils = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
vergen = '3.0.4'

[dependencies]
futures = { version = '0.3.9', features = ['compat'] }
jsonrpc-core = '15.0.0'
structopt = '0.3.8'
hex-literal = '0.3.1'

# local node-specific dependencies
datahighway-runtime = { version = '3.0.5', path = '../runtime' }

# Substrate dependencies
frame-benchmarking = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
frame-benchmarking-cli = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
module-primitives = { version = '3.0.5', default-features = false, path = '../pallets/primitives' }
pallet-authority-discovery = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
pallet-democracy = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
pallet-im-online = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
pallet-transaction-payment-rpc = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sc-authority-discovery = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sc-basic-authorship = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sc-cli = { features = ['wasmtime'], git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sc-client-api = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sc-consensus-epochs = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sc-chain-spec = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sc-keystore = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sc-consensus = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sc-consensus-aura = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sc-consensus-slots = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sc-executor = { features = ['wasmtime'], git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sc-rpc = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sc-rpc-api = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sc-service = {  git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e', default-features = false, features = ['wasmtime'] }
sc-sync-state-rpc = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sc-transaction-pool = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sp-api = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sp-authority-discovery = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sp-block-builder = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sp-blockchain = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sp-consensus = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sp-consensus-aura = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sp-core = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sc-finality-grandpa = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sc-finality-grandpa-rpc = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sp-finality-grandpa = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sp-inherents = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sp-keystore = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sc-network = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sp-runtime = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sp-transaction-pool = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sp-consensus-babe = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sc-consensus-babe = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sc-consensus-babe-rpc = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
sc-telemetry = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }
substrate-frame-rpc-system = { git = 'https://github.com/paritytech/substrate', rev = '319d244f6a2601a1a6f62595fcc7f5976615d50e' }

serde_json = '1.0.41'
serde = { version = '1.0.102', features = ['derive'] }

[dev-dependencies]
# futures = '0.3.9'

[features]
default = []
