[package]
authors = ['MXC Foundation GmbH <https://t.me/mxcfoundation>', 'Luke Schoen <luke@mxc.org>', 'Ilya Beregovskiy <ilya@mxc.org>']
build = 'build.rs'
edition = '2018'
name = 'datahighway'
version = '1.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[[bin]]
name = 'datahighway'

[dependencies]
structopt = '0.3.8'

# Substrate dependencies
sc-cli = { version = '0.9.0', features = ['wasmtime'] }
sp-core = '3.0.0'
sc-executor = { version = '0.9.0', features = ['wasmtime'] }
sc-service = { version = '0.9.0', features = ['wasmtime'] }
sc-telemetry = { version = '3.0.0' }
sc-keystore = { version = '3.0.0' }
sp-inherents = { version = '3.0.0' }
sc-transaction-pool = { version = '3.0.0' }
sp-transaction-pool = { version = '3.0.0' }
sc-consensus-babe = { version = '0.9.0' }
sp-consensus-babe = { version = '0.9.0' }
sc-consensus = { version = '0.9.0' }
sp-consensus = { version = '0.9.0' }
sc-finality-grandpa = { version = '0.9.0' }
sp-finality-grandpa = { version = '3.0.0' }
sc-client-api = { version = '3.0.0' }
sp-runtime = { version = '3.0.0' }

sc-consensus-epochs = { version = '0.9.0' }
sc-chain-spec = { version = '3.0.0' }
sc-consensus-babe-rpc = { version = '0.9.0' }
serde_json = '1.0.47'
serde = { version = '1.0.119', features = ['derive'], optional = true }

# These dependencies are used for the node template's RPCs
jsonrpc-core = '15.1.0'

sc-rpc = '3.0.0'
sp-api = '3.0.0'
sc-rpc-api = '0.9.0'
sp-blockchain = '3.0.0'
sp-block-builder = '3.0.0'
sc-basic-authorship = '0.9.0'
substrate-frame-rpc-system = '3.0.0'
pallet-transaction-payment-rpc = '3.0.0'

# These dependencies are used for runtime benchmarking
frame-benchmarking = '3.1.0'
frame-benchmarking-cli = '3.0.0'

# local dependencies
datahighway-runtime = { path = '../runtime', version = '1.0.0' }

[build-dependencies]
substrate-build-script-utils = '3.0.0'

[features]
default = []
