[package]
authors = ['MXC Foundation gGmbH <https://t.me/mxcfoundation>', 'Luke Schoen <luke@mxc.org>', 'Ilya Beregovskiy <ilya@mxc.org>']
build = 'build.rs'
edition = '2018'
name = 'datahighway'
version = '3.0.5'

[[bin]]
name = 'datahighway'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-build-script-utils = { version = '3.0.0' }
# substrate-build-script-utils = { git = 'https://github.com/paritytech/substrate', rev = 'deac6324a16fc4128b94a7b4c3826eebcb86917f' }
vergen = '3.0.4'

[dependencies]
futures = { version = '0.3.9', features = ['compat'] }
jsonrpc-core = '15.0.0'
structopt = '0.3.8'
hex-literal = '0.3.1'

# local node-specific dependencies
datahighway-runtime = { version = '3.0.5', path = '../runtime' }

# Substrate dependencies
frame-benchmarking = { version = '4.0.0-dev' }
frame-benchmarking-cli = { version = '4.0.0-dev' }
module-primitives = { version = '3.0.5', default-features = false, path = '../pallets/primitives' }
pallet-authority-discovery = { version = '4.0.0-dev' }
pallet-democracy = { version = '4.0.0-dev' }
pallet-im-online = { version = '4.0.0-dev' }
pallet-transaction-payment-rpc = { version = '4.0.0-dev' }
sc-authority-discovery = { version = '0.10.0-dev' }
sc-basic-authorship = { version = '0.10.0-dev' }
sc-cli = { version = '0.10.0-dev', features = ['wasmtime'] }
sc-client-api = { version = '4.0.0-dev' }
sc-chain-spec = { version = '4.0.0-dev' }
sc-keystore = { version = '4.0.0-dev' }
sc-consensus = { version = '0.10.0-dev' }
sc-consensus-aura = { version = '0.10.0-dev' }
sc-consensus-epochs = { version = '0.10.0-dev' }
sc-consensus-slots = { version = '0.10.0-dev' }
sc-consensus-babe = { version = '0.10.0-dev' }
sc-consensus-babe-rpc = { version = '0.10.0-dev' }
sc-consensus-uncles = { version = '0.10.0-dev' }
sc-telemetry = { version = '4.0.0-dev' }
sc-executor = { version = '0.10.0-dev', features = ['wasmtime'] }
sc-rpc = { version = '4.0.0-dev' }
sc-rpc-api = { version = '0.10.0-dev' }
sc-service = { version = '0.10.0-dev', default-features = false, features = ['wasmtime'] }
sc-sync-state-rpc = { version = '0.10.0-dev' }
sc-transaction-pool = { version = '4.0.0-dev' }
sc-transaction-pool-api = { version = '4.0.0-dev' }
sp-api = { version = '4.0.0-dev', default-features = false }
sp-authority-discovery = { version = '4.0.0-dev', default-features = false }
sp-block-builder = { version = '4.0.0-dev', default-features = false }
sp-blockchain = { version = '4.0.0-dev' }
sp-consensus = { version = '0.10.0-dev' }
sp-consensus-aura = { version = '0.10.0-dev', default-features = false }
sp-core = { version = '4.0.0-dev' }
sc-finality-grandpa = { version = '0.10.0-dev' }
sc-finality-grandpa-rpc = { version = '0.10.0-dev' }
sp-finality-grandpa = { version = '4.0.0-dev' }
sp-inherents = { version = '4.0.0-dev', default-features = false }
sp-keystore = { version = '0.10.0-dev' }
sc-network = { version = '0.10.0-dev' }
sp-runtime = { version = '4.0.0-dev' }
sp-timestamp = { version = '4.0.0-dev' }
sp-authorship = { version = '4.0.0-dev', default-features = false }
sp-consensus-babe = { version = '0.10.0-dev' }
substrate-frame-rpc-system = { version = '4.0.0-dev' }

serde_json = '1.0.41'
serde = { version = '1.0.126', features = ['derive'] }

[dev-dependencies]
# futures = '0.3.9'

[features]
default = []
