[package]
name = "lockdrop-runtime-api"
version = "0.1.0"
authors = ['Ilya Beregovskiy']
edition = "2018"

[dependencies]
sp-api = { git = 'https://github.com/paritytech/substrate', rev = 'c666a251691300c1651075a3b59ba1cf59c5a664', default-features = false}

[features]
default = ["std"]
std = [
	"sp-api/std",
]
