[package]
name = "lockdrop-runtime-api"
version = "0.1.0"
authors = ['Ilya Beregovskiy']
edition = "2018"

[dependencies]
sp-api = { git = 'https://github.com/paritytech/substrate', rev = 'a76cc733f4fe895d8be002ce13fdae0ca1ba555e', default-features = false}

[features]
default = ["std"]
std = [
	"sp-api/std",
]
