[package]
name = "lockdrop-runtime-api"
version = "0.1.0"
authors = ['Ilya Beregovskiy']
edition = "2018"

[dependencies]
sp-api = { git = 'https://github.com/paritytech/substrate', rev = '1c842c45a1564acc1a2ba0cbd4d0467570a16d4a', default-features = false}

[features]
default = ["std"]
std = [
	"sp-api/std",
]
