[package]
name = "lockdrop-runtime-api"
version = "0.1.0"
authors = ['Ilya Beregovskiy']
edition = "2018"

[dependencies]
sp-api = { git = 'https://github.com/paritytech/substrate', rev = '1309f52711e2bb2dc019a22d802b771b7bd3e4ef', default-features = false}

[features]
default = ["std"]
std = [
	"sp-api/std",
]
