[package]
name = "lockdrop-runtime-api"
version = "0.1.0"
authors = ['Ilya Beregovskiy']
edition = "2018"

[dependencies]
sp-api = { git = 'https://github.com/paritytech/substrate', rev = '1e045f218db16027197dc11ac04220896321260f', default-features = false}

[features]
default = ["std"]
std = [
	"sp-api/std",
]
