[package]
name = "lockdrop-runtime-api"
version = "0.1.0"
authors = ['Ilya Beregovskiy']
edition = "2021"

[dependencies]
sp-api = { git = 'https://github.com/paritytech/substrate', rev = 'c6f86e139d57a37511af769c49b426c2fff3f260', default-features = false}

[features]
default = ["std"]
std = [
	"sp-api/std",
]
