[package]
name = "lockdrop-runtime-api"
version = "0.1.0"
authors = ['Ilya Beregovskiy']
edition = "2021"

[dependencies]
sp-api = { git = 'https://github.com/paritytech/substrate', rev = '3f3cc90c06a1e0a7a93dbd5b660a475e9b4a783e', default-features = false}

[features]
default = ["std"]
std = [
	"sp-api/std",
]
