[package]
name = "lockdrop-runtime-api"
version = "0.1.0"
authors = ['Ilya Beregovskiy']
edition = "2018"

[dependencies]
sp-api = { git = 'https://github.com/paritytech/substrate', rev = 'deac6324a16fc4128b94a7b4c3826eebcb86917f', default-features = false}

[features]
default = ["std"]
std = [
	"sp-api/std",
]
