[package]
name = "lockdrop-runtime-api"
version = "0.1.0"
authors = ['Ilya Beregovskiy']
edition = "2018"

[dependencies]
sp-api = { git = 'https://github.com/paritytech/substrate', rev = '22f09c602704aeee2b59b14f427f73f6cb8b5e2f', default-features = false}

[features]
default = ["std"]
std = [
	"sp-api/std",
]
