[package]
name = "lockdrop-runtime-api"
version = "0.1.0"
authors = ['Ilya Beregovskiy']
edition = "2018"

[dependencies]
sp-api = { git = 'https://github.com/paritytech/substrate', rev = '28107d402cb88cf50119c4ecb16555fcacf3a3e6', default-features = false}

[features]
default = ["std"]
std = [
	"sp-api/std",
]
