[package]
name = "lockdrop-runtime-api"
version = "0.1.0"
authors = ['Ilya Beregovskiy']
edition = "2018"

[dependencies]
sp-api = { git = 'https://github.com/paritytech/substrate', rev = '993907f9deb180795b291ba752b9c204165d74dc', default-features = false}

[features]
default = ["std"]
std = [
	"sp-api/std",
]
