[package]
name = "lockdrop-runtime-api"
version = "0.1.0"
authors = ['Ilya Beregovskiy']
edition = "2018"

[dependencies]
sp-api = { git = 'https://github.com/DataHighway-DHX/substrate', rev = '527101517d0ad67780131def8d227de51e503a89', default-features = false}

[features]
default = ["std"]
std = [
	"sp-api/std",
]
