[package]
name = "lockdrop-runtime-api"
version = "0.1.0"
authors = ['Ilya Beregovskiy']
edition = "2018"

[dependencies]
sp-api = { git = 'https://github.com/paritytech/substrate', rev = 'f794140759d8bf9aa03483d663e86f2272090009', default-features = false}

[features]
default = ["std"]
std = [
	"sp-api/std",
]
