[package]
name = "lockdrop-runtime-api"
version = "0.1.0"
authors = ['Ilya Beregovskiy']
edition = "2018"

[dependencies]
sp-api = { git = 'https://github.com/DataHighway-DHX/substrate', rev = '852bab073407b65b5e3e461baaa0541c4e0bc3d6', default-features = false}

[features]
default = ["std"]
std = [
	"sp-api/std",
]
