[package]
name = "lockdrop-runtime-api"
version = "0.1.0"
authors = ['Ilya Beregovskiy']
edition = "2018"

[dependencies]
sp-api = { git = 'https://github.com/paritytech/substrate', rev = '6d82c02611c51a5c54d60e02c3c104b10aa3ae71', default-features = false}

[features]
default = ["std"]
std = [
	"sp-api/std",
]
