[package]
name = "lockdrop-runtime-api"
version = "0.1.0"
authors = ['Ilya Beregovskiy']
edition = "2018"

[dependencies]
sp-api = { git = 'https://github.com/paritytech/substrate', rev = '1d5abf01abafdb6c15bcd0172f5de09fd87c5fbf', default-features = false}

[features]
default = ["std"]
std = [
	"sp-api/std",
]
