[package]
name = "roaming-networks"
version = "0.1.0"
authors = ["Luke Schoen"]
edition = "2018"

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'log/std',
    'pallet-balances/std',
    'pallet-randomness-collective-flip/std',
    'pallet-transaction-payment/std',
    'serde',
    'safe-mix/std',
    'sp-core/std',
    'sp-io/std',
    'sp-runtime/std',
    'sp-std/std',
    'roaming-operators/std'
]

[dependencies]
codec = { version = '1.0.0', package = 'parity-scale-codec', default-features = false, features = ['derive'] }
safe-mix = { version = '1.0.0', default-features = false }
frame-support = { rev = 'a22d57f9c371efb10b015afcc132a95f083cd326', git = 'https://github.com/paritytech/substrate.git', default_features = false }
frame-system = { rev = 'a22d57f9c371efb10b015afcc132a95f083cd326', git = 'https://github.com/paritytech/substrate.git', default_features = false }
pallet-balances = { rev = 'a22d57f9c371efb10b015afcc132a95f083cd326', git = 'https://github.com/paritytech/substrate.git', default_features = false }
pallet-randomness-collective-flip = { rev = 'a22d57f9c371efb10b015afcc132a95f083cd326', git = 'https://github.com/paritytech/substrate.git', default_features = false }
pallet-transaction-payment = { rev = 'a22d57f9c371efb10b015afcc132a95f083cd326', git = 'https://github.com/paritytech/substrate.git', default_features = false }
sp-core = { rev = 'a22d57f9c371efb10b015afcc132a95f083cd326', git = 'https://github.com/paritytech/substrate.git', default_features = false }
sp-io = { rev = 'a22d57f9c371efb10b015afcc132a95f083cd326', git = 'https://github.com/paritytech/substrate.git', default_features = false }
sp-runtime = { rev = 'a22d57f9c371efb10b015afcc132a95f083cd326', git = 'https://github.com/paritytech/substrate.git', default_features = false }
sp-std = { rev = 'a22d57f9c371efb10b015afcc132a95f083cd326', git = 'https://github.com/paritytech/substrate.git', default_features = false }

log = { version = '0.4.8' }
serde = { version = '1.0', optional = true }

roaming-operators = { default_features = false, package = 'roaming-operators', path = '../roaming-operators' }

[dev-dependencies]
