[package]
name = "lockdrop-rpc"
version = "0.1.0"
authors = ["Ilya Beregovskiy"]
edition = "2018"

[dependencies]
web3 = "0.13.0"
codec = { version = '2.0.0', package = 'parity-scale-codec', default-features = false, features = ['derive'] }
safe-mix = { version = '1.0.0', default-features = false }
frame-support = { git = 'https://github.com/paritytech/substrate', rev = '6d82c02611c51a5c54d60e02c3c104b10aa3ae71', default-features = false }
frame-system = { git = 'https://github.com/paritytech/substrate', rev = '6d82c02611c51a5c54d60e02c3c104b10aa3ae71', default-features = false }
pallet-balances = { git = 'https://github.com/paritytech/substrate', rev = '6d82c02611c51a5c54d60e02c3c104b10aa3ae71', default-features = false }
pallet-randomness-collective-flip = { git = 'https://github.com/paritytech/substrate', rev = '6d82c02611c51a5c54d60e02c3c104b10aa3ae71', default-features = false }
pallet-transaction-payment = { git = 'https://github.com/paritytech/substrate', rev = '6d82c02611c51a5c54d60e02c3c104b10aa3ae71', default-features = false }
sp-core = { git = 'https://github.com/paritytech/substrate', rev = '6d82c02611c51a5c54d60e02c3c104b10aa3ae71', default-features = false }
sp-io = { git = 'https://github.com/paritytech/substrate', rev = '6d82c02611c51a5c54d60e02c3c104b10aa3ae71', default-features = false }
sp-runtime = { git = 'https://github.com/paritytech/substrate', rev = '6d82c02611c51a5c54d60e02c3c104b10aa3ae71', default-features = false }
sp-std = { git = 'https://github.com/paritytech/substrate', rev = '6d82c02611c51a5c54d60e02c3c104b10aa3ae71', default-features = false }

log = { version = '0.4.8' }
serde = { version = '1.0.101', optional = true, features = ['derive'] }

[dev-dependencies]
