[package]
name = 'module-primitives'
version = '3.0.5'
authors = ['Laminar Developers <hello@laminar.one>', 'MXC Foundation GmbH <https://t.me/mxcfoundation>', 'Luke Schoen']
edition = '2018'

[dependencies]
serde = { version = '1.0.101', optional = true, features = ['derive'] }
codec = { version = '2.0.0', package = 'parity-scale-codec', default-features = false, features = ['derive'] }
sp-core = { git = 'https://github.com/paritytech/substrate', rev = 'f794140759d8bf9aa03483d663e86f2272090009', default-features = false }
sp-runtime = { git = 'https://github.com/paritytech/substrate', rev = 'f794140759d8bf9aa03483d663e86f2272090009', default-features = false }
bitmask = { version = '0.5.0', default-features = false }
sp-std = { git = 'https://github.com/paritytech/substrate', rev = 'f794140759d8bf9aa03483d663e86f2272090009', default-features = false }

[features]
default = ['std']
std = [
    'bitmask/std',
    'codec/std',
    'serde',
    'sp-core/std',
    'sp-runtime/std',
    'sp-std/std',
]
