[package]
name = 'module-primitives'
version = '2.0.0'
authors = ['Laminar Developers <hello@laminar.one>', 'MXC Foundation GmbH <https://t.me/mxcfoundation>']
edition = '2018'

[dependencies]
bitmask = { version = '0.5.0', default-features = false }
serde = { version = '1.0.101', optional = true, features = ['derive'] }
codec = { package = 'parity-scale-codec', version = '1.0.0', default-features = false }
sp-core = { version = '2.0.0', default-features = false }
sp-runtime = { version = '2.0.0', default-features = false }
sp-std = { version = '2.0.0', default-features = false }

[features]
default = ['std']
std = [
	'bitmask/std',
	'serde',
	'codec/std',
	'sp-core/std',
	'sp-runtime/std',
	'sp-std/std',
]
