[package]
name = 'module-primitives'
version = '0.0.1'
authors = ['Laminar Developers <hello@laminar.one>', 'MXC Foundation GmbH <https://t.me/mxcfoundation>', 'Luke Schoen']
edition = '2018'

[dependencies]
serde = { version = '1.0.101', optional = true, features = ['derive'] }
codec = { package = 'parity-scale-codec', version = '1.0.0', default-features = false }
bitmask = { version = '0.5.0', default-features = false }

[dependencies.sp-runtime]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
branch = "rococo-v1"
version = '2.0.0'

[dependencies.sp-std]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
branch = "rococo-v1"
version = '2.0.0'

[features]
default = ['std']
std = [
	'bitmask/std',
	'codec/std',
	'serde',
	'sp-runtime/std',
	'sp-std/std',
]
