[package]
name = "mining-speed-boosts-eligibility-hardware-mining"
version = "0.1.0"
authors = ["Luke Schoen"]
edition = "2018"

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'randomness-collective-flip/std',
    'sp-io/std',
    'sp-std/std',
    'system/std',
    'transaction-payment/std',
    'roaming-operators/std',
    'mining-speed-boosts-rates-hardware-mining/std',
    'mining-speed-boosts-configuration-hardware-mining/std',
    'mining-speed-boosts-sampling-hardware-mining/std',
]

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.0.0'

[dependencies.frame-support]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-support'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.randomness-collective-flip]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-randomness-collective-flip'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.sp-io]
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'
version = '2.0.0'

[dependencies.sp-std]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-std'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.system]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-system'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.transaction-payment]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-transaction-payment'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dev-dependencies.balances]
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-balances'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.roaming-operators]
default_features = false
package = 'roaming-operators'
path = '../../../../roaming/roaming-operators'

[dependencies.mining-speed-boosts-rates-hardware-mining]
default_features = false
package = 'mining-speed-boosts-rates-hardware-mining'
path = '../../../../mining/mining-speed-boosts/rates/hardware-mining'

[dependencies.mining-speed-boosts-configuration-hardware-mining]
default_features = false
package = 'mining-speed-boosts-configuration-hardware-mining'
path = '../../../../mining/mining-speed-boosts/configuration/hardware-mining'

[dependencies.mining-speed-boosts-sampling-hardware-mining]
default_features = false
package = 'mining-speed-boosts-sampling-hardware-mining'
path = '../../../../mining/mining-speed-boosts/sampling/hardware-mining'
