[package]
name = "mining-eligibility-proxy"
version = "3.0.5"
authors = ["Luke Schoen"]
edition = "2018"

[features]
default = ['std']
std = [
    'chrono/std',
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'module-primitives/std',
    'safe-mix/std',
    'pallet-balances/std',
    'pallet-randomness-collective-flip/std',
    'pallet-timestamp/std',
    'pallet-transaction-payment/std',
    'pallet-treasury/std',
    'sp-core/std',
    'sp-io/std',
    'sp-runtime/std',
    'sp-std/std',

    'account-set/std',
    'membership-supernodes/std',
]

[dependencies]
codec = { version = '2.0.0', package = 'parity-scale-codec', default-features = false, features = ['derive'] }
frame-support = { git = 'https://github.com/paritytech/substrate', rev = '1c842c45a1564acc1a2ba0cbd4d0467570a16d4a', default-features = false }
frame-system = { git = 'https://github.com/paritytech/substrate', rev = '1c842c45a1564acc1a2ba0cbd4d0467570a16d4a', default-features = false }
module-primitives = { version = '3.0.5', default-features = false, path = '../../../primitives' }
safe-mix = { version = '1.0.0', default-features = false }
pallet-balances = { git = 'https://github.com/paritytech/substrate', rev = '1c842c45a1564acc1a2ba0cbd4d0467570a16d4a', default-features = false }
pallet-randomness-collective-flip = { git = 'https://github.com/paritytech/substrate', rev = '1c842c45a1564acc1a2ba0cbd4d0467570a16d4a', default-features = false }
pallet-timestamp = { git = 'https://github.com/paritytech/substrate', rev = '1c842c45a1564acc1a2ba0cbd4d0467570a16d4a', default_features = false }
pallet-transaction-payment = { git = 'https://github.com/paritytech/substrate', rev = '1c842c45a1564acc1a2ba0cbd4d0467570a16d4a', default-features = false }
pallet-treasury = { git = 'https://github.com/paritytech/substrate', rev = '1c842c45a1564acc1a2ba0cbd4d0467570a16d4a', default-features = false }
sp-core = { git = 'https://github.com/paritytech/substrate', rev = '1c842c45a1564acc1a2ba0cbd4d0467570a16d4a', default-features = false }
sp-io = { git = 'https://github.com/paritytech/substrate', rev = '1c842c45a1564acc1a2ba0cbd4d0467570a16d4a', default-features = false }
sp-runtime = { git = 'https://github.com/paritytech/substrate', rev = '1c842c45a1564acc1a2ba0cbd4d0467570a16d4a', default-features = false }
sp-std = { git = 'https://github.com/paritytech/substrate', rev = '1c842c45a1564acc1a2ba0cbd4d0467570a16d4a', default-features = false }
chrono = { version = '0.4.19', default_features = false }

account-set = { path = '../../../../traits/account-set', default-features = false }
membership-supernodes = { path = '../../../membership/supernodes', default-features = false }

[dev-dependencies]
